### ISSUE TITLE
Update Shopper-Context RAML

### ISSUE THREAD

**Issue by johnboxall** [SalesforceCommerceCloud/commerce-sdk-isomorphic#119]
The bundled RAML definition for the Shopper Context API is out of date.

The API is out of beta and the return types of objects have changed.

* https://salesforcecommercecloud.github.io/commerce-sdk-isomorphic/classes/shoppercontexts.shoppercontexts-1.html#createshoppercontext
* https://developer.salesforce.com/docs/commerce/commerce-api/references/shopper-context?meta=createShopperContext

**Comment by joeluong-sfcc** [comment]
We'll be releasing soon for this PR: https://github.com/SalesforceCommerceCloud/commerce-sdk-isomorphic/pull/115, so we'll pull the upstream RAML down and update it then

**Comment by tarcang** [comment]
Shopper Context has been updated with the new release.
