### ISSUE TITLE
Custom request parameters not supported

### ISSUE THREAD

**Issue by stm-dschulz** [SalesforceCommerceCloud/commerce-sdk-isomorphic#126]
When using custom parameters like

`api.shopperProducts.getProducts({
	parameters: {
		ids,
		allImages: true,
                foo: 'bar'
	}
})`

the `foo` parameter is not included in the related request.

**Is there any way / workaround to use custom parameter atm ?**

If not - it would be really helpful if this could be added.
As SCAPI supports hooks to customize request handling and response its really a must that the SDK is supporting custom parameters. It's a common practice to do customizations in hooks based on the presence or with the value of a custom parameter.

**Comment by joeluong-sfcc** [comment]
Hi @stm-dschulz, thanks for filing this issue. I don't believe there is currently a way to pass custom parameters through the SDK. A potential work around would to be calling the endpoint directly for the calls that require custom parameters. I've created a work item in our backlog to bring this up to the team.

**Comment by stm-dschulz** [comment]
Hi @joeluong-sfcc, thx for checking.
Already discovered that custom parameters are not support by the API itself. But they are planned for the future. So would be cool if they will be supported by the SDK then.
