### ISSUE TITLE
[BUG] Unable to login when password contains certains characters

### ISSUE THREAD

**Issue by jpuxan-osf** [SalesforceCommerceCloud/commerce-sdk-isomorphic#127]
# Summary

Is not possible to login into your user account in PWA if your password contains certain characters such as î·¬èº

# Steps To Reproduce

1. Create an account where the password has any of the following characters î·¬èº
2. Logout
3. Login to the just created account

# Expected result

Be able to login

# Actual result

Login screen shows "Incorrect username or password, please try again."

# System Information (as applicable)

**Browser:** Firefox & Chrome
**pwa-kit version:** develop
**Desktop OS:** Windows 10

# Additional information
See the fix for PWA 2.7.1: https://github.com/SalesforceCommerceCloud/pwa-kit/issues/1243
![2023-06-02_12h00_52](https://github.com/SalesforceCommerceCloud/commerce-sdk-isomorphic/assets/57627419/481539b8-cfe6-486f-97ea-c375bfc7ef6b)

**Comment by joeluong-sfcc** [comment]
Hi @jpuxan-osf, thanks for filing an issue on the PWA kit as well. As this bug is already being tracked in the PWA kit repo, I will close out this issue and the PWA kit team will follow up on this bug when it is resolved.
