### ISSUE TITLE
Change log should warn about side effects of moving from `XMLHttpRequest` to `fetch in `1.10.0`

### ISSUE THREAD

**Issue by johnboxall** [SalesforceCommerceCloud/commerce-sdk-isomorphic#129]
In release 1.10.0, we changed the underlying transported used in browsers from `XMLHttpRequest` to `fetch`:

https://github.com/SalesforceCommerceCloud/commerce-sdk-isomorphic/blob/main/CHANGELOG.md#v1100

If prior to 1.10.0, you were passing `fetchOptions: {redirect: 'manual'}` as a server-side performance optimization to prevent following then this upgrade can cause a regression as this option is silently ignored by `XMLHttpRequest`, but DOES impact `fetch`.

Commonly, this would cause SLAS `authorizeCustomer` requests to fail with `opaqueredirect` errors.

Folks upgrading should either:

a) remove these optimizations and use the provided helper methods provided by the SDK which implement them or ...
b) update their code to only provide `fetchOptions.redirect = 'manual'` server side (and not client side)

**Comment by joeluong-sfcc** [comment]
Fixed with https://github.com/SalesforceCommerceCloud/commerce-sdk-isomorphic/pull/132
