### ISSUE TITLE
How to use it? docs?

### ISSUE THREAD

**Issue by ParthChugh** [SalesforceCommerceCloud/commerce-sdk-isomorphic#49]
Can someone add proper steps, how to use it

**Comment by wjhsf** [comment]
* Documentation for the SDK is available [here](https://salesforcecommercecloud.github.io/commerce-sdk-isomorphic/).
* A learning module for the [node.js SDK](https://github.com/SalesforceCommerceCloud/commerce-sdk) is available on [Trailhead](https://trailhead.salesforce.com/content/learn/modules/b2c-commerce-sdk). Note that the node.js SDK has features and APIs not present in the isomorphic SDK, so not everything from that module is applicable.
* Further information about the APIs is available at the [Commerce Cloud Developer Center](https://developer.commercecloud.com/s/commerce-api).

**Comment by ParthChugh** [comment]
@wjhsf 
`
**config.js**

import {CLIENT_ID, GET_ORG_ID, GET_SHORT_CODE, GET_SITE_ID} from './connector';
const https = require("https");
const config = {
  proxy: 'http://localhost:3000/mobify/proxy/capi',
  parameters: {
    clientId: CLIENT_ID,
    organizationId: GET_ORG_ID,
    shortCode: GET_SHORT_CODE,
    siteId: GET_SITE_ID
  },
};
export { config as default };
`
`
import { ShopperCustomers } from "commerce-sdk-isomorphic";
import config from '../../config';
const customerClient = new ShopperCustomers(config);

export async function getGuestToken() {
  const authResponse = await customerClient.authorizeCustomer({
    body: { type: 'guest' },
  }, true)
  
  return authResponse.headers.get('authorization'); 
}
`

getGuestToken() is always giving 200, but the authorization token is not available in the headers

**Comment by wjhsf** [comment]
Are you executing this code from `http://localhost:3000`? The requests will only work if they are from the origin specified in the proxy (or if you disable CORS, but that comes with potential security concerns).

**Comment by ParthChugh** [comment]
Yes, I'm executing this from http://localhost:3000, If I disable CORS it is working as expected, if I add any proxy it doesn't work

**Comment by wjhsf** [comment]
If that is the case, then it is likely an issue with your proxy, not with the SDK. To identify the issue, you can examine the requests that are being made from the browser console, whatever logs your proxy server provides, or the full `authResponse` in the code sample you provided.

**Comment by ParthChugh** [comment]
@wjhsf , Can you please refer to the response, the proxy seems to be fine 

**Reponse**
![Screenshot 2021-07-10 at 11](https://user-images.githubusercontent.com/21955236/125153204-c81e9900-e16f-11eb-8c4b-81b8f0ceb36a.png)

**Request** 

![Screenshot 2021-07-10 at 11 14 11 AM](https://user-images.githubusercontent.com/21955236/125153297-5a26a180-e170-11eb-8841-2a649e843842.png)

**Comment by wjhsf** [comment]
Follow these steps to verify that your configuration is correct. If everything is configured correctly, then the last step will launch a small react app in your browser that will execute a product search and display the first result.

1. Clone this repository. `git clone git@github.com:SalesforceCommerceCloud/commerce-sdk-isomorphic.git && cd commerce-sdk-isomorphic`
2. Edit the config in `src/environment/config.js` and the `proxy` field in `package.json`
3. Build the SDK. `yarn install && yarn renderTemplates`
4. Run the dev server. `yarn start`

**Comment by ParthChugh** [comment]
I'm able to run the server, but it is behaving the same
![image](https://user-images.githubusercontent.com/21955236/125334501-121e9f00-e369-11eb-8b01-a02b6d163056.png)

Is it something with my configurations? 

Have changed the proxy based on the shortcode, have also changed the configuration in config.js, when I try disabling CORS it works properly

**Comment by wjhsf** [comment]
If you are having configuration issues, you can ask for help in the [Commerce Developer Community](https://developer.commercecloud.com/s/group/0F93k000000UOtSCAW/commerce-developer-community).

**Comment by ParthChugh** [comment]
It was not the configuration issue, it is more like an implementation issue, there is no way I could find to call the APIs on the client-side, so instead of that I moved the functions to the express layer, then it is giving proper results.


For reference - 
![image](https://user-images.githubusercontent.com/21955236/126035713-c4008408-b19e-4660-a062-9495300209ea.png)
