### ISSUE TITLE
Custom `User-Agent` used in browser produces warning in Chrome

### ISSUE THREAD

**Issue by johnboxall** [SalesforceCommerceCloud/commerce-sdk-isomorphic#60]
1.4.1 began setting the `User-Agent` header: https://github.com/SalesforceCommerceCloud/commerce-sdk-isomorphic/commit/53747ac5fcb973332be3d194c48c13a7ed5d765f

It sets the header both in Node.js and browser based environments.

Chrome does not support this and will give you a warning:

> Refused to set unsafe header "user-agent"

The related Chrome bug is here: https://bugs.chromium.org/p/chromium/issues/detail?id=571722

_Much older versions of the `fetch` spec did not support setting the `User-Agent`, but it appears to have been added in ~2015: https://github.com/whatwg/fetch/issues/37. Safari and Firefox both seem to support this behaviour._

---

_I don't think this issue is important to resolve, but wanted to leave my notes here for others potentially encountering it!_

**Comment by wjhsf** [comment]
Thanks for documenting this issue! There's not a whole lot we can do about it, as it's a limitation on the browser itself.

As a bit of bonus information, the warning actually comes from [cross-fetch](https://www.npmjs.com/package/cross-fetch). Using Chrome's native fetch results in the custom user agent being silently ignored.
