### ISSUE TITLE
Handle errors in `loginRegisteredUserB2C`

### ISSUE THREAD

**Issue by johnboxall** [SalesforceCommerceCloud/commerce-sdk-isomorphic#82]
The current implementation of `capi.helpers.loginRegisteredUserB2C` assumes `authenticateCustomer` succeeds, when in practice, there are many reasons it could fail:

1. Bad credentials
2. Bad SLAS setup
3. Service is down etc.

https://github.com/SalesforceCommerceCloud/commerce-sdk-isomorphic/blob/1b40c04cedcdd470ebc10e313707f784b2d7d66f/src/static/helpers/slasHelper.ts#L236-L238

We should consider guarding against these kinds of errors by checking `response` was successful between grabbing the code/usid.

As an aside, this function is also impacted by: https://github.com/SalesforceCommerceCloud/commerce-sdk-isomorphic/issues/73

This function should be updated to also not make a request to `redirectURI` if running server side.

**Comment by tarcang** [comment]
Hello! #90 intends to fix this. It has just been merged.
