### ISSUE TITLE
Slas helper logout doesn't work

### ISSUE THREAD

**Issue by kevinxh** [SalesforceCommerceCloud/commerce-sdk-isomorphic#88]
Hey team, I'm trying to use the SLAS helper logout here: https://github.com/SalesforceCommerceCloud/commerce-sdk-isomorphic/blob/1b40c04cedcdd470ebc10e313707f784b2d7d66f/src/static/helpers/slasHelper.ts#L284-L300

According to the API reference, this endpoint requires Authorization header to be filled with the access token, it looks like there is no way to pass the header to the helper.

![Screen Shot 2022-06-02 at 5 57 50 PM](https://user-images.githubusercontent.com/10948652/171765646-8798ce84-f7a0-4a60-bd27-465cc27805c4.png)

**Comment by joeluong-sfcc** [comment]
Hi @kevinxh thanks for creating this issue! I've created a work item in our backlog to solve this and we'll circle you back in when this issue is resolved.

**Comment by joeluong-sfcc** [comment]
Resolved with https://github.com/SalesforceCommerceCloud/commerce-sdk-isomorphic/pull/97 closing this issue out
